// The OpenNext build generates this file before Wrangler bundles the worker.
// It owns all normal Next.js HTTP handling; this wrapper only adds cron.
// @ts-ignore generated by opennextjs-cloudflare build
import { default as handler } from "./.open-next/worker.js"
import { runScheduledJobs } from "./lib/jobs/scheduled"
import type { KVLike } from "./lib/unshieldings/shared"

interface CloudflareEnv {
  SUPPLY_CACHE?: KVLike
}

type ScheduledController = {
  cron: string
  scheduledTime?: number
}

type ExecutionContext = {
  waitUntil(promise: Promise<unknown>): void
}

type WorkerExport = {
  fetch: (request: Request, env: CloudflareEnv, ctx: ExecutionContext) => Response | Promise<Response>
  scheduled: (
    controller: ScheduledController,
    env: CloudflareEnv,
    ctx: ExecutionContext
  ) => void | Promise<void>
}

export default {
  fetch: handler.fetch,

  async scheduled(
    controller: ScheduledController,
    env: CloudflareEnv,
    ctx: ExecutionContext
  ) {
    ctx.waitUntil(
      runScheduledJobs(env, controller.cron).then((results) => {
        console.log("[scheduler]", JSON.stringify(results))
      })
    )
  },
} satisfies WorkerExport

// Re-export OpenNext Durable Objects generated by the adapter.
// @ts-ignore generated by opennextjs-cloudflare build when needed
export {
  BucketCachePurge,
  DOQueueHandler,
  DOShardedTagCache,
} from "./.open-next/worker.js"
